#
# Basic KallistiOS skeleton / test program
# Copyright (C)2001-2004 Megan Potter
#

# Put the filename of the output binary here
TARGET = random.elf

# List all of your C files here, but change the extension to ".o"
OBJS = random.o

CFLAGS = -std=c99

include $(KOS_BASE)/Makefile.rules
