#
# Basic KallistiOS skeleton / test program
# Copyright (C) 2001-2004 Megan Potter
# Copyright (C) 2024 Falco Girgis
#   

# Put the filename of the output binary here
TARGET = hello.elf

# List all of your C or C++ files here, but change the extension to ".o"
OBJS = hello.o

# Optional path to a directory of resources to bundle within your ELF binary.
# Its contents are accessible via the "/rd/" virtual directory at runtime.
#KOS_ROMDISK_DIR = romdisk

# Include the common KOS Makefile rules and configuration
include $(KOS_BASE)/Makefile.rules
