# KallistiOS ##version##
#
# examples/dreamcast/sd/ext2fs/Makefile
#

TARGET = sd-ext2fs.elf
OBJS = sd-ext2fs.o
LDLIBS = -lkosext2fs

# Uncomment the next line to enable write support in the example.
#CPPFLAGS = -DENABLE_WRITE

include $(KOS_BASE)/Makefile.rules
