# KallistiOS ##version##
#
# video/palmenu/Makefile
#

# Put the filename of the output binary here
TARGET = palmenu.elf

# List all of your C files here, but change the extension to ".o"
OBJS = palmenu.o

include $(KOS_BASE)/Makefile.rules
