#
# KallistiOS network/speedtest example
# 
# Copyright (C) 2024 Andress Barajas
#

TARGET = speedtest.elf
OBJS = speedtest.o server.o handle_request.o romdisk.o
KOS_ROMDISK_DIR = romdisk
KOS_BUILD_SUBARCHS = pristine

include $(KOS_BASE)/Makefile.rules
