#
# vmu_game test program
# (c)2020 BBHoodsta
#   

# Put the filename of the output binary here
TARGET = vmu_game.elf

# List all of your C files here, but change the extension to ".o"
OBJS = vmu_game.o romdisk.o

KOS_ROMDISK_DIR = romdisk

include $(KOS_BASE)/Makefile.rules
