#
# Nehe16 example adapted from KGL
# (c)2013-2014 Josh Pearson
# (c)2001 Benoit Miller
#   

TARGET = nehe16.elf
OBJS = nehe16.o pvr-texture.o romdisk.o
KOS_ROMDISK_DIR = romdisk
LDLIBS = -lGL

include $(KOS_BASE)/Makefile.rules
