# KallistiOS ##version##
#
# libmp3/Makefile
# (c)2001 Megan Potter
# (c)2023 Ruslan Rostovtsev
#

OBJS = snd_iface.o \
	snd_sfxmgr.o \
	snd_stream.o \
	snd_mem.o \
	snd_pcm_split.o

KOS_CFLAGS += -I $(KOS_BASE)/kernel/arch/dreamcast/include/dc/sound

include $(KOS_BASE)/Makefile.prefab
