#
# Parallax font test
# (c)2002 Megan Potter
#   

TARGET = font.elf
OBJS = font.o romdisk.o
KOS_ROMDISK_DIR = romdisk
LDLIBS = -lparallax -lpng -ljpeg -lkmg -lz -lkosutils

include $(KOS_BASE)/Makefile.rules
