#
# Stack Protector Test/Example
# Copyright (C) 2021 Lawrence Sebald
# Copyright (C) 2024 Falco Girgis
#

TARGET = stackprotector.elf
OBJS = stackprotector.o
KOS_CFLAGS += -fstack-protector-all
KOS_GCCVER_MIN = 4.0.0

include $(KOS_BASE)/Makefile.rules
