#
# KGL Specular Lighting Example (c)2013-2014 Josh Pearson
#  

TARGET = specular.elf
OBJS = specular.o vector.o input.o pvr-texture.o font.o timer.o romdisk.o
KOS_ROMDISK_DIR = romdisk
LDLIBS = -lKGL

include $(KOS_BASE)/Makefile.rules
