#
# KallistiGL Radial Blur test program
# (c)2014 Josh Pearson
#   

TARGET = radial_blur.elf
OBJS = radial_blur.o pvr-texture.o romdisk.o
KOS_ROMDISK_DIR = romdisk
LDLIBS = -lKGL

include $(KOS_BASE)/Makefile.rules
