#
# Font Test program makefile by Peter Hatch
# based on
# KallistiGL test program
# (c)2001 Megan Potter
#   

TARGET = fnt_test.elf
OBJS = fnt_test.o romdisk.o
LDLIBS = -ldcplib -lstdc++
KOS_ROMDISK_DIR = romdisk

include $(KOS_BASE)/Makefile.rules
