# Put the filename of the output binary here
TARGET = dns-client.elf

# List all of your C files here, but change the extension to ".o"
OBJS = dns-client.o

# Only build for pristine subarch (aka. "dreamcast")
KOS_BUILD_SUBARCHS = pristine

include $(KOS_BASE)/Makefile.rules
