#
# KallistiOS ##version##
#
# examples/dreamcast/gldc/2D_tex_quad/Makefile
# Copyright (C) 2024 Jason Rost (OniEnzeru)
#


# Directories
KOS_ROMDISK_DIR := romdisk

# File aggregators
OBJS		:= main.o romdisk.o

# Compiler Flags
CXXFLAGS	:= -std=c++20
LDLIBS 		:= -lstb_image -lGL -lkmg -lkosutils -lstdc++

TARGET = 2D_tex_quad.elf

include $(KOS_BASE)/Makefile.rules
