#
# OpenGL Dreamcast MipMap Example
# (c)2014 Josh Pearson
#   

TARGET = gl-mipmap.elf
OBJS = gl-mipmap.o pvr-texture.o romdisk.o
KOS_ROMDISK_DIR = romdisk
LDLIBS = -lKGL

include $(KOS_BASE)/Makefile.rules
