# KallistiOS ##version##
#
# basic/threading/compiler_tls/Makefile
#
# Copyright (C) 2001 Megan Potter
# Copyright (C) 2023 Colton Pawielski
#

TARGET = compiler_tls.elf
OBJS = compiler_tls.o

include $(KOS_BASE)/Makefile.rules
