#
# vmu_pkg test program
# (c)2002 Megan Potter
#   

# Put the filename of the output binary here
TARGET = vmu.elf

# List all of your C files here, but change the extension to ".o"
OBJS = vmu.o romdisk.o

KOS_ROMDISK_DIR = romdisk

include $(KOS_BASE)/Makefile.rules
