#
# C++ Concurrency Test/Example
# Copyright (C) 2023, 2024 Falco Girgis
#

TARGET = concurrency.elf
OBJS = concurrency.o
CXXFLAGS = -std=c++20
LDLIBS = -lstdc++
KOS_GCCVER_MIN = 12.0.0

include $(KOS_BASE)/Makefile.rules
