#
# DC Clock App
# Based on Peter Hatch's Font Test
# (c)2002 Megan Potter
#   

TARGET = clock.elf
OBJS = clock.o romdisk.o
KOS_ROMDISK_DIR = romdisk

CXXFLAGS = -std=gnu++17
LDLIBS = -ldcplib -lstdc++

include $(KOS_BASE)/Makefile.rules
