#
# Basic KallistiOS skeleton / test program
# (c)2001 Megan Potter
#   

# Put the filename of the output binary here
TARGET = ping.elf

# List all of your C files here, but change the extension to ".o"
OBJS = ping.o

# Only build for pristine subarch (aka. "dreamcast")
KOS_BUILD_SUBARCHS = pristine

include $(KOS_BASE)/Makefile.rules
