#
# KallistiGL test program
# (c)2013-2014 Josh PH3NOM Pearson
# (c)2001 Megan Potter
#   

TARGET = gltest.elf
OBJS = gltest.o pvr-texture.o romdisk.o
KOS_ROMDISK_DIR = romdisk
LDLIBS = -lGL -lpcx -lkosutils

include $(KOS_BASE)/Makefile.rules
