#
# PVR/Parallax vertex DMA test program
#   

TARGET = serpent.elf
OBJS = serpent.o perfmeter.o romdisk.o
KOS_ROMDISK_DIR = romdisk
LDLIBS = -lparallax -lkosutils

include $(KOS_BASE)/Makefile.rules
