#
# OpenGL (c)2013-2014 Josh PH3NOM Pearson
#
# scissor test
# (c)2002 Paul Boese
#

TARGET = scissor.elf
OBJS = scissor.o pvr-texture.o romdisk.o
KOS_ROMDISK_DIR = romdisk
LDLIBS = -lKGL -lpcx -lkosutils

include $(KOS_BASE)/Makefile.rules
