#
# Basic KallistiOS skeleton / test program
# Copyright (C)2001-2004 Megan Potter
#

# Put the filename of the output binary here
TARGET = devroot.elf

# List all of your C files here, but change the extension to ".o"
OBJS = devroot.o

include $(KOS_BASE)/Makefile.rules
