#
# C++ out-of-memory demonstration
# (c)2023 Falco Girgis
#

TARGET = out_of_memory.elf
OBJS = out_of_memory.o
CXXFLAGS = -fexceptions -std=c++11
LDLIBS = -lstdc++

include $(KOS_BASE)/Makefile.rules
