#
# LibADX Test
# Copyright (C) 2011-2013 Josh 'PH3NOM' Pearson <ph3nom.dcmc@gmail.com>
# Copyright (C) 2024 The KOS Team and contributors
#

TARGET = libADXplay.elf
OBJS = libADXplay.o romdisk.o
KOS_ROMDISK_DIR = romdisk
LDLIBS = -lADX

include $(KOS_BASE)/Makefile.rules
