#
# KallistiGL test program in C++
# (c)2001 Megan Potter
#   

TARGET = gltest.elf
OBJS = gltest.o romdisk.o
LDLIBS = -lGL -lkosutils -lstdc++
KOS_ROMDISK_DIR = romdisk

include $(KOS_BASE)/Makefile.rules
