# KallistiOS ##version##
#
# loadable/Makefile.prefab
# Copyright (C) 2000, 2003 Megan Potter
# Copyright (C) 2024 Ruslan Rostovtsev
#

include $(KOS_BASE)/Makefile.rules

LDLIBS=-lkallisti_exports

all: dbg-$(TARGET)

$(TARGET): LDFLAGS+=-Wl,-d -Wl,-r -Wl,-S -Wl,-x -Wl,--no-gc-sections -nostartfiles -nodefaultlibs -Wl,-T $(KOS_BASE)/loadable/shlelf_dc.xr

dbg-$(TARGET): LDLIBS+=$(DBG_LIBS)

dbg-$(TARGET): LDFLAGS+=-g -Wl,-Ttext=0x00000000 -e _start -nostartfiles -nodefaultlibs

# dbg-$(TARGET) checks for missing symbols (and fully links with an offset
# of zero so we can do tracebacks later)
dbg-$(TARGET): $(OBJS)
	kos-cc -o $@ $^ $(LDFLAGS) -Wl,--start-group $(LDLIBS) -Wl,--end-group
