# KallistiOS ##version##
#
# examples/dreamcast/sound/multi-stream/Makefile
#

TARGET = multistream.elf
OBJS = romdisk.o main.o
KOS_ROMDISK_DIR = romdisk
LDLIBS = -lwav

include $(KOS_BASE)/Makefile.rules
