# KallistiOS ##version##
#
# examples/dreamcast/dreameye/sd/Makefile
#

TARGET = dreameye-sd.elf
OBJS = dreameye-sd.o

# Compile cleanly, or die trying!
CFLAGS = -Werror -W -std=gnu99

LDLIBS = -lkosext2fs

include $(KOS_BASE)/Makefile.rules
