# KallistiOS ##version##
#
# pthread/general/Makefile
# Copyright (C) 2023 Lawrence Sebald
#

TARGET = general_pthread_test.elf
OBJS = general_pthread_test.o
LDLIBS = -lpthread

include $(KOS_BASE)/Makefile.rules
