#
# OpenGL Dreamcast Multi-Texture Example
# (c)2014 Josh Pearson
#   

TARGET = gl-multitex-elements.elf
OBJS = gl-multitex-elements.o pvr-texture.o romdisk.o
KOS_ROMDISK_DIR = romdisk
LDLIBS = -lKGL

include $(KOS_BASE)/Makefile.rules
