#
# OpenGL Dreamcast Vertex Arrays Example
# (c)2014 Josh PH3NOM Pearson
#   

TARGET = gl-elements.elf
OBJS = gl-elements.o pvr-texture.o romdisk.o
KOS_ROMDISK_DIR = romdisk
LDLIBS = -lKGL

include $(KOS_BASE)/Makefile.rules
