#
# OpenGL Dreamcast Example
# (c)2014 Josh PH3NOM Pearson
#   

TARGET = gltest.elf
OBJS = gltest.o pvr-texture.o romdisk.o
KOS_ROMDISK_DIR = romdisk
LDLIBS = -lKGL

include $(KOS_BASE)/Makefile.rules
